In [2]:
import numpy as np
array = np.arange(1, 11)

In [3]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [5]:
array[array > 5]

array([ 6,  7,  8,  9, 10])

In [6]:
condition = array <= 4

In [7]:
array[condition]

array([1, 2, 3, 4])

In [8]:
new_condition = (array != 6) & (array > 7)

In [9]:
array[new_condition]

array([ 8,  9, 10])

In [10]:
# Arithmetic Operations in Numpy
array = np.arange(1, 11)

In [11]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:
array + 2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [13]:
array - 2

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [14]:
array * 2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
array / 2 

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [16]:
(array / 2) + 12

array([12.5, 13. , 13.5, 14. , 14.5, 15. , 15.5, 16. , 16.5, 17. ])

In [17]:
array ** 2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
array/array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [19]:
np.subtract(array, 2)

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8])

In [20]:
np.add(array, 2)

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [21]:
np.multiply(array, 2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [22]:
np.divide(array, 2)

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [23]:
array % 2

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 0], dtype=int32)

In [24]:
array ** 3

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [25]:
np.power(array, 3)

array([   1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [26]:
np.sqrt(2)

1.4142135623730951

In [27]:
np.sqrt(array)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [28]:
array % 5

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [29]:
np.mod(array, 5)

array([1, 2, 3, 4, 0, 1, 2, 3, 4, 0], dtype=int32)

In [30]:
np.sin(342)

0.4201396822393068

In [31]:
np.cos(342)

-0.907459446701534

In [32]:
np.log(342)

5.834810737062605

In [33]:
np.log(10)

2.302585092994046

In [34]:
# statistical functions in numpy
array = np.arange(1, 11)

In [35]:
array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [36]:
np.sum(array)	# sum of all elements

55

In [37]:
np.mean(array)	# mean of all elements

5.5

In [38]:
np.median(array)	# median of all elements

5.5

In [39]:
np.average(array)	# average of all elements

5.5

In [40]:
np.min(array)	# minimum value

1

In [41]:
np.max(array)	# maximum value

10

In [42]:
np.std(array)	# standard deviation

2.8722813232690143

In [43]:
np.var(array)	# variance

8.25

In [44]:
np.percentile(array, 50)	# 50th percentile

5.5

In [45]:
np.sqrt(np.var(array))	# standard deviation

2.8722813232690143

In [46]:
# solving second order equation
# 2x1 + x2 = 5
# -3x1 + 6x2 = 0
coefficients = np.array([[2, 1], [-3, 6]])

In [47]:
coefficients

array([[ 2,  1],
       [-3,  6]])

In [48]:
output = np.array([5, 0])

In [49]:
np.linalg.solve(coefficients, output)

array([2., 1.])