In [1]:
import numpy as np

In [2]:
array = np.arange(0,11)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
array[3]

3

In [5]:
array[-9]

2

In [7]:
variable = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [8]:
variable

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [9]:
variable[0,0]

5

In [10]:
variable[2,1]#[raw,index]

40

In [11]:
variable[-1,-3]

35

In [12]:
# Slicing One-Dimensional Numpy Array
# sintax [sraty,stop,step]
example = np.arange(10,20)

In [13]:
example

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [15]:
example[2]

12

In [16]:
example[2:6]

array([12, 13, 14, 15])

In [17]:
example[3:]

array([13, 14, 15, 16, 17, 18, 19])

In [18]:
example[:-3:3]

array([10, 13, 16])

In [19]:
#Slicing Two Dimesional Numpy array
array = np.arange(30).reshape(6,5)

In [21]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [22]:
array[2,:] # to get all the element of the row

array([10, 11, 12, 13, 14])

In [23]:
array[2]

array([10, 11, 12, 13, 14])

In [24]:
array[1]

array([5, 6, 7, 8, 9])

In [25]:
array[:,1] # to get column

array([ 1,  6, 11, 16, 21, 26])

In [26]:
array[:,0]

array([ 0,  5, 10, 15, 20, 25])

In [27]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [28]:
array[1:4,3:3]#array[start:stop:step,start:stop:step]

array([], shape=(3, 0), dtype=int32)

In [29]:
array[1:4,0:3]

array([[ 5,  6,  7],
       [10, 11, 12],
       [15, 16, 17]])

In [30]:
array[0::2,0::2]

array([[ 0,  2,  4],
       [10, 12, 14],
       [20, 22, 24]])

In [31]:
# Assigning value to one - dimentional arrays
variable = np.array([0,1,2,3,4,5,6,7,8,9])

In [32]:
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
variable[7] = 12

In [34]:
variable

array([ 0,  1,  2,  3,  4,  5,  6, 12,  8,  9])

In [35]:
variable[7] = 7

In [36]:
variable

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [38]:
variable[0:5] = 10

In [39]:
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [40]:
variable [5:]

array([5, 6, 7, 8, 9])

In [41]:
array[5:]=20,30,40,50,60

In [42]:
variable

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [43]:
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [20, 30, 40, 50, 60]])

In [44]:
 #fancy indexing of One-Dimentional Arrays
fancy = np.arange(0,50,5)

In [45]:
fancy

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45])

In [46]:
fancy[1]

5

In [47]:
fancy[3]

15

In [48]:
fancy[5]

25

In [49]:
[fancy[1],fancy[2],fancy[3]]

[5, 10, 15]

In [50]:
indexes = [1,3,5]

In [51]:
fancy[indexes]

array([ 5, 15, 25])

In [52]:
array = np.array([1,3,5])

In [53]:
array

array([1, 3, 5])

In [54]:
fancy[array]

array([ 5, 15, 25])

In [55]:
# fancy indexing in two dimentional array
variable = np.zeros((10,10),dtype="int")

In [56]:
variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [58]:
variable.shape

(10, 10)

In [60]:
variable.shape[0]

10

In [61]:
row = variable.shape[0]

In [62]:
for i in range(row):
    variable[i] = i

In [63]:

variable

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [6, 6, 6, 6, 6, 6, 6, 6, 6, 6],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [9, 9, 9, 9, 9, 9, 9, 9, 9, 9]])

In [64]:
list1 = [1,3,5,7]

In [65]:
variable[list1]


array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7]])

In [66]:
list2 = [8,5,3,7,3]

In [67]:
variable[list2]

array([[8, 8, 8, 8, 8, 8, 8, 8, 8, 8],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3],
       [7, 7, 7, 7, 7, 7, 7, 7, 7, 7],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [68]:
example = np.arange(1,17).reshape((4,4))

In [69]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [71]:
example[[0,3]]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [72]:
example[:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [73]:
example[[0,3],[1,2]]

array([ 2, 15])

In [74]:
row = [0,2,3,1]
column = [3,0,2,1]


In [75]:
example[row,column]

array([ 4,  9, 15,  6])

In [76]:
# Combining Fancy index with Normal Indexing
example = np.arange(1,17).reshape((4,4))

In [77]:
example


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [78]:
example[1,[1,3]]

array([6, 8])

In [79]:
example[[0,3],1]

array([ 2, 14])

In [80]:
# Combining Fancy index with Normal Slicing
example= np.arange(1,17).reshape((4,4))

In [81]:
example

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [82]:
example[0:,[1,2]]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [83]:
example[1:3,[1,2]]

array([[ 6,  7],
       [10, 11]])