In [1]:
#CREATING PANDAS DATAFRAME FROM SCRATCH
# DATAFRAME IS A MULTIDIMENSIONAL DATA SSTRUCTURE
import pandas as pd


In [5]:
list_example = [1,2,3,43,423,4,5,6,7,8,9,10]

In [6]:
list_example

[1, 2, 3, 43, 423, 4, 5, 6, 7, 8, 9, 10]

In [8]:
pd.DataFrame(data=list_example, columns=['values'],dtype=float)

values
0      1.0
1      2.0
2      3.0
3     43.0
4    423.0
5      4.0
6      5.0
7      6.0
8      7.0
9      8.0
10     9.0
11    10.0

In [9]:
# CREATING A DATAFRAME WITH NUMPY ARRAY
import numpy as np

In [14]:
array_example = np.random.randint(0,50,(10,5))

In [15]:
array_example

array([[ 1, 22, 12, 13, 16],
       [36, 24,  7, 41,  2],
       [37,  4, 14,  1, 10],
       [ 8, 46,  0, 13, 47],
       [13, 12, 18, 17, 16],
       [27, 15, 37, 13, 32],
       [ 4, 28, 49, 28, 33],
       [30, 36, 29, 12,  6],
       [ 2,  4, 18, 31, 10],
       [43, 34,  3, 37, 21]])

In [16]:
df = pd.DataFrame(data=array_example, index = ['A','B','C','D','E','F','G','H','I','J'], columns=['V','W','X','Y','Z']) # INDEX IS THE ROWS AND COLUMNS ARE THE COLUMNS

In [17]:
df

V   W   X   Y   Z
A   1  22  12  13  16
B  36  24   7  41   2
C  37   4  14   1  10
D   8  46   0  13  47
E  13  12  18  17  16
F  27  15  37  13  32
G   4  28  49  28  33
H  30  36  29  12   6
I   2   4  18  31  10
J  43  34   3  37  21

In [20]:
#CREATING A DATAFRAME WITH DICTIONARY
x= np.random.randint(0,50, size = 6)

In [21]:
x


array([17,  8,  9, 37, 24, 46])

In [24]:
x= np.random.randint(0,50, size = 6)
y= np.random.randint(0,50, size = 6)
z= np.random.randint(0,50, size = 6)
t= np.random.randint(0,50, size = 6)

In [23]:
x,y,z

(array([45,  1, 26, 19, 49, 32]),
 array([16,  2, 41, 31,  1, 43]),
 array([26, 36,  3,  0, 13, 45]))

In [25]:
dict_example = {'val1':x, 'val2':y, 'val3':z, 'val4':t}

In [26]:
dict_example

{'val1': array([22, 36, 36,  7,  2, 35]),
 'val2': array([43, 42, 25, 33, 25, 18]),
 'val3': array([42, 13, 10,  4, 16, 22]),
 'val4': array([ 1, 46, 13, 39,  5, 30])}

In [27]:
df= pd.DataFrame(data=dict_example)

In [28]:
df

val1  val2  val3  val4
0    22    43    42     1
1    36    42    13    46
2    36    25    10    13
3     7    33     4    39
4     2    25    16     5
5    35    18    22    30

In [29]:
#Examine properties of the Dataframe
df.shape

(6, 4)

In [31]:
df.head()

val1  val2  val3  val4
0    22    43    42     1
1    36    42    13    46
2    36    25    10    13
3     7    33     4    39
4     2    25    16     5

In [32]:
df.head(2)

val1  val2  val3  val4
0    22    43    42     1
1    36    42    13    46

In [34]:
df.tail()

val1  val2  val3  val4
1    36    42    13    46
2    36    25    10    13
3     7    33     4    39
4     2    25    16     5
5    35    18    22    30

In [35]:
df.tail

<bound method NDFrame.tail of    val1  val2  val3  val4
0    22    43    42     1
1    36    42    13    46
2    36    25    10    13
3     7    33     4    39
4     2    25    16     5
5    35    18    22    30>

In [36]:
df.tail(2)

val1  val2  val3  val4
4     2    25    16     5
5    35    18    22    30

In [37]:
df.columns

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [38]:
list = df.columns

In [39]:
list

Index(['val1', 'val2', 'val3', 'val4'], dtype='object')

In [40]:
[i for i in df.columns]

['val1', 'val2', 'val3', 'val4']

In [41]:
df.columns = ['A','B','C','D'] # changing the column names

In [42]:
df

A   B   C   D
0  22  43  42   1
1  36  42  13  46
2  36  25  10  13
3   7  33   4  39
4   2  25  16   5
5  35  18  22  30